/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MemberDashboardRouteImport } from './routes/member.dashboard'
import { Route as MemberJobsRouteImport } from './routes/member.jobs'
import { Route as MemberPostJobRouteImport } from './routes/member.post-job'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesChatIdRouteImport } from './routes/messages.$chatId'
import { Route as SupportReportRouteImport } from './routes/support.report'
import { Route as WorkerApplicationsRouteImport } from './routes/worker.applications'
import { Route as WorkerDashboardRouteImport } from './routes/worker.dashboard'
import { Route as WorkerFindJobsRouteImport } from './routes/worker.find-jobs'
import { Route as MemberJobJobIdRouteImport } from './routes/member.job.$jobId'
import { Route as WorkerJobJobIdRouteImport } from './routes/worker.job.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberDashboardRoute = MemberDashboardRouteImport.update({
  id: '/member/dashboard',
  path: '/member/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberJobsRoute = MemberJobsRouteImport.update({
  id: '/member/jobs',
  path: '/member/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberPostJobRoute = MemberPostJobRouteImport.update({
  id: '/member/post-job',
  path: '/member/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesChatIdRoute = MessagesChatIdRouteImport.update({
  id: '/messages/$chatId',
  path: '/messages/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportReportRoute = SupportReportRouteImport.update({
  id: '/support/report',
  path: '/support/report',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerApplicationsRoute = WorkerApplicationsRouteImport.update({
  id: '/worker/applications',
  path: '/worker/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerDashboardRoute = WorkerDashboardRouteImport.update({
  id: '/worker/dashboard',
  path: '/worker/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerFindJobsRoute = WorkerFindJobsRouteImport.update({
  id: '/worker/find-jobs',
  path: '/worker/find-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberJobJobIdRoute = MemberJobJobIdRouteImport.update({
  id: '/member/job/$jobId',
  path: '/member/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerJobJobIdRoute = WorkerJobJobIdRouteImport.update({
  id: '/worker/job/$jobId',
  path: '/worker/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/earnings': typeof EarningsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/jobs': typeof MemberJobsRoute
  '/member/post-job': typeof MemberPostJobRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/support/report': typeof SupportReportRoute
  '/worker/applications': typeof WorkerApplicationsRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/find-jobs': typeof WorkerFindJobsRoute
  '/messages/': typeof MessagesIndexRoute
  '/member/job/$jobId': typeof MemberJobJobIdRoute
  '/worker/job/$jobId': typeof WorkerJobJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/earnings': typeof EarningsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/jobs': typeof MemberJobsRoute
  '/member/post-job': typeof MemberPostJobRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/support/report': typeof SupportReportRoute
  '/worker/applications': typeof WorkerApplicationsRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/find-jobs': typeof WorkerFindJobsRoute
  '/messages': typeof MessagesIndexRoute
  '/member/job/$jobId': typeof MemberJobJobIdRoute
  '/worker/job/$jobId': typeof WorkerJobJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/earnings': typeof EarningsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/member/dashboard': typeof MemberDashboardRoute
  '/member/jobs': typeof MemberJobsRoute
  '/member/post-job': typeof MemberPostJobRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/support/report': typeof SupportReportRoute
  '/worker/applications': typeof WorkerApplicationsRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/find-jobs': typeof WorkerFindJobsRoute
  '/messages/': typeof MessagesIndexRoute
  '/member/job/$jobId': typeof MemberJobJobIdRoute
  '/worker/job/$jobId': typeof WorkerJobJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community-guidelines'
    | '/earnings'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/member/dashboard'
    | '/member/jobs'
    | '/member/post-job'
    | '/messages/$chatId'
    | '/support/report'
    | '/worker/applications'
    | '/worker/dashboard'
    | '/worker/find-jobs'
    | '/messages/'
    | '/member/job/$jobId'
    | '/worker/job/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community-guidelines'
    | '/earnings'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/member/dashboard'
    | '/member/jobs'
    | '/member/post-job'
    | '/messages/$chatId'
    | '/support/report'
    | '/worker/applications'
    | '/worker/dashboard'
    | '/worker/find-jobs'
    | '/messages'
    | '/member/job/$jobId'
    | '/worker/job/$jobId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community-guidelines'
    | '/earnings'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/member/dashboard'
    | '/member/jobs'
    | '/member/post-job'
    | '/messages/$chatId'
    | '/support/report'
    | '/worker/applications'
    | '/worker/dashboard'
    | '/worker/find-jobs'
    | '/messages/'
    | '/member/job/$jobId'
    | '/worker/job/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  EarningsRoute: typeof EarningsRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  MemberDashboardRoute: typeof MemberDashboardRoute
  MemberJobsRoute: typeof MemberJobsRoute
  MemberPostJobRoute: typeof MemberPostJobRoute
  MessagesChatIdRoute: typeof MessagesChatIdRoute
  SupportReportRoute: typeof SupportReportRoute
  WorkerApplicationsRoute: typeof WorkerApplicationsRoute
  WorkerDashboardRoute: typeof WorkerDashboardRoute
  WorkerFindJobsRoute: typeof WorkerFindJobsRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  MemberJobJobIdRoute: typeof MemberJobJobIdRoute
  WorkerJobJobIdRoute: typeof WorkerJobJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/dashboard': {
      id: '/member/dashboard'
      path: '/member/dashboard'
      fullPath: '/member/dashboard'
      preLoaderRoute: typeof MemberDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/jobs': {
      id: '/member/jobs'
      path: '/member/jobs'
      fullPath: '/member/jobs'
      preLoaderRoute: typeof MemberJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/post-job': {
      id: '/member/post-job'
      path: '/member/post-job'
      fullPath: '/member/post-job'
      preLoaderRoute: typeof MemberPostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$chatId': {
      id: '/messages/$chatId'
      path: '/messages/$chatId'
      fullPath: '/messages/$chatId'
      preLoaderRoute: typeof MessagesChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/report': {
      id: '/support/report'
      path: '/support/report'
      fullPath: '/support/report'
      preLoaderRoute: typeof SupportReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/applications': {
      id: '/worker/applications'
      path: '/worker/applications'
      fullPath: '/worker/applications'
      preLoaderRoute: typeof WorkerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/dashboard': {
      id: '/worker/dashboard'
      path: '/worker/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof WorkerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/find-jobs': {
      id: '/worker/find-jobs'
      path: '/worker/find-jobs'
      fullPath: '/worker/find-jobs'
      preLoaderRoute: typeof WorkerFindJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/job/$jobId': {
      id: '/member/job/$jobId'
      path: '/member/job/$jobId'
      fullPath: '/member/job/$jobId'
      preLoaderRoute: typeof MemberJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/job/$jobId': {
      id: '/worker/job/$jobId'
      path: '/worker/job/$jobId'
      fullPath: '/worker/job/$jobId'
      preLoaderRoute: typeof WorkerJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  EarningsRoute: EarningsRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  MemberDashboardRoute: MemberDashboardRoute,
  MemberJobsRoute: MemberJobsRoute,
  MemberPostJobRoute: MemberPostJobRoute,
  MessagesChatIdRoute: MessagesChatIdRoute,
  SupportReportRoute: SupportReportRoute,
  WorkerApplicationsRoute: WorkerApplicationsRoute,
  WorkerDashboardRoute: WorkerDashboardRoute,
  WorkerFindJobsRoute: WorkerFindJobsRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  MemberJobJobIdRoute: MemberJobJobIdRoute,
  WorkerJobJobIdRoute: WorkerJobJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
